%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.0.2

-ifndef(common_pb).
-define(common_pb, true).

-define(common_pb_gpb_version, "4.0.2").

-ifndef('SCORE_ATTR_PB_H').
-define('SCORE_ATTR_PB_H', true).
-record(score_attr,
        {type                   :: 'buff' | integer(), % = 1, enum t_score_attr
         value                  :: non_neg_integer() | undefined % = 2, 32 bits
        }).
-endif.

-ifndef('USER_SUMMARY_PB_H').
-define('USER_SUMMARY_PB_H', true).
-record(user_summary,
        {uid                    :: non_neg_integer() % = 1, 32 bits
        }).
-endif.

-ifndef('SCORE_PB_H').
-define('SCORE_PB_H', true).
-record(score,
        {uid                    :: non_neg_integer(), % = 1, 32 bits
         total_score = 0        :: non_neg_integer(), % = 2, 32 bits
         attack_score = 0       :: non_neg_integer(), % = 3, 32 bits
         event_score = 0        :: non_neg_integer(), % = 4, 32 bits
         attrs                  :: #score_attr{} | undefined % = 5
        }).
-endif.

-ifndef('ATTACK_ATTR_PB_H').
-define('ATTACK_ATTR_PB_H', true).
-record(attack_attr,
        {type                   :: 'crit' | integer(), % = 1, enum t_attack_attr
         value                  :: non_neg_integer() | undefined % = 2, 32 bits
        }).
-endif.

-ifndef('ATTACK_PB_H').
-define('ATTACK_PB_H', true).
-record(attack,
        {type = normal          :: 'normal' | integer(), % = 1, enum t_attack
         from_uid               :: non_neg_integer(), % = 2, 32 bits
         to_uid                 :: non_neg_integer(), % = 3, 32 bits
         times = 1              :: non_neg_integer(), % = 4, 32 bits
         attrs                  :: #attack_attr{} | undefined % = 5
        }).
-endif.

-ifndef('EVENT_ATTR_PB_H').
-define('EVENT_ATTR_PB_H', true).
-record(event_attr,
        {type                   :: 'crit' | integer(), % = 1, enum t_event_attr
         value                  :: non_neg_integer() | undefined % = 2, 32 bits
        }).
-endif.

-ifndef('EVENT_PB_H').
-define('EVENT_PB_H', true).
-record(event,
        {type = teacher_catched :: 'teacher_catched' | integer(), % = 1, enum t_event
         affected_uids = []     :: [non_neg_integer()] | undefined, % = 2, 32 bits
         times = 0              :: non_neg_integer(), % = 3, 32 bits
         attrs                  :: #event_attr{} | undefined % = 4
        }).
-endif.

-ifndef('BATTLE_PB_H').
-define('BATTLE_PB_H', true).
-record(battle,
        {attack                 :: #attack{} | undefined, % = 1
         event                  :: #event{} | undefined % = 2
        }).
-endif.

-ifndef('EVENT_INFO_PB_H').
-define('EVENT_INFO_PB_H', true).
-record(event_info,
        {type                   :: 'teacher_catched' | integer(), % = 1, enum t_event
         start_time             :: non_neg_integer(), % = 2, 32 bits
         duration = 0           :: non_neg_integer(), % = 3, 32 bits
         attrs                  :: #event_attr{} | undefined % = 4
        }).
-endif.

-endif.
