%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.0.2

-ifndef(game_pb).
-define(game_pb, true).

-define(game_pb_gpb_version, "4.0.2").

-ifndef('USER_PB_H').
-define('USER_PB_H', true).
-record(user,
        {uid                    :: non_neg_integer(), % = 1, 32 bits
         password = "00000000"  :: iolist()         % = 2
        }).
-endif.

-endif.
